### ISSUE TITLE
R03. Receive a notification if my proposal is hidden

### ISSUE THREAD

**Issue by microstudi** [stadtluzern/decidim-letterbox-damagereporting#19] opened 2022-09-13 08:52 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
As a user, I would like to receive a notification if my proposal is hidden.

**Mock up**

**Does this issue could impact on users private data?**

**Acceptance criteria**
- [ ] 

**Technical specifications**
https://github.com/openpoke/decidim/issues/22

**Implementation**
- [x] https://github.com/openpoke/decidim/pull/29
- [x] https://github.com/openpoke/decidim/pull/30

**Testing**

**Additional context**
Metadecidim proposal: https://meta.decidim.org/processes/roadmap/f/122/proposals/17116

**Comment by paarals** [comment] 2022-10-06 10:58
looks like that:
![imatge](https://user-images.githubusercontent.com/40388743/194295892-d6b42d4b-5ecf-4890-9907-781f6e392298.png)

steps to reproduce:
1. create a proposal 
2. moderate proposal
3. hide proposal
4. as an author, i received this mail

as you have to **moderate** you can give an explanation
![imatge](https://user-images.githubusercontent.com/40388743/194296146-ee9e1846-06b7-4886-a3f2-fd13cd1db796.png)

**Comment by paarals** [comment] 2022-10-11 14:33
closed by sprint 3

**Closed by paarals** 2022-10-11 14:33 UTC
Labels: must-have, decidim-feature
